#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    print("PATH {}".format(conf.env.PATH)) 
    conf.env.PATH = ['/usr/local/opt/protobuf@2.5/bin']
    conf.env.PKG_CONFIG_PATH = ['/usr/local/opt/protobuf@2.5/lib/pkgconfig']
    conf.load(['protoc'])

def build(bld):
    bld(name = 'proto_includes',
        features = 'protoc cxx', 
        source = bld.path.ant_glob('*.proto'),
        includes = '.')
